### ISSUE TITLE
Requirements up-to-date?

### ISSUE THREAD

**Issue by Jorge-C** [biocore/scikit-bio#1147]
Creating a new environment in a new computer, I get this test failures after `pip install -e .`

```
======================================================================
ERROR: Failure: ImportError (No module named 'httpretty')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jc/anaconda/envs/tst/lib/python3.5/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/jc/anaconda/envs/tst/lib/python3.5/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/jc/anaconda/envs/tst/lib/python3.5/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/jc/anaconda/envs/tst/lib/python3.5/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/jc/anaconda/envs/tst/lib/python3.5/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/home/jc/anaconda/envs/tst/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/jc/bipy/skbio/io/tests/test_util.py", line 18, in <module>
    import httpretty
ImportError: No module named 'httpretty'
```

**Comment by Jorge-C** [comment]
Ah, it is in `extras_require` in setup.py, but I don't know how to install it directly (i.e., doing something like pip install skbio[test]` for developers). Of course, the steps in contributing.md work using the requirements file work, so I'll close this!
