### ISSUE TITLE
nose seems to be required at runtime

### ISSUE THREAD

**Issue by wwood** [biocore/scikit-bio#1214]
Hi,

I came across this error while installing a package dependent on skbio within a virtualenv (python 2.7). The error basically boils down to this:
```
Traceback (most recent call last):
(snip)
    import skbio.tree
  File "/srv/projects/abisko/shotgun_abundance/96_graftm_virtualenv/graftm_virtualenv/lib/python2.7/site-packages/skbio/__init__.py", line 11, in <module>
    from skbio.util import TestRunner
  File "/srv/projects/abisko/shotgun_abundance/96_graftm_virtualenv/graftm_virtualenv/lib/python2.7/site-packages/skbio/util/__init__.py", line 71, in <module>
    from ._testing import (get_data_path, TestRunner,
  File "/srv/projects/abisko/shotgun_abundance/96_graftm_virtualenv/graftm_virtualenv/lib/python2.7/site-packages/skbio/util/_testing.py", line 15, in <module>
    from nose import core
ImportError: No module named nose
```
Easy enough to workaround, of course, by installing nose.

Thanks,
ben

**Comment by jairideout** [comment]
Thanks for catching this, nose should be added to setup.py's `install_requires`. I'll work on fixing this.
