### ISSUE TITLE
RDA and composition test failures

### ISSUE THREAD

**Issue by jairideout** [biocore/scikit-bio#1267]
Master is currently failing the following RDA and composition tests:

RDA:

```shell
$ python skbio/stats/ordination/tests/test_redundancy_analysis.py
.FF
======================================================================
FAIL: test_scaling1 (__main__.TestRDAResults)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "skbio/stats/ordination/tests/test_redundancy_analysis.py", line 110, in test_scaling1
    decimal=6)
  File "/Users/jairideout/dev/scikit-bio/skbio/util/_testing.py", line 1035, in assert_ordination_results_equal
    decimal=decimal)
  File "/Users/jairideout/dev/scikit-bio/skbio/util/_testing.py", line 1083, in _assert_frame_equal
    npt.assert_almost_equal(left_values, right_values, decimal=decimal)
  File "/Users/jairideout/miniconda/envs/scikit-bio/lib/python3.5/site-packages/numpy/testing/utils.py", line 497, in assert_almost_equal
    return assert_array_almost_equal(actual, desired, decimal, err_msg)
  File "/Users/jairideout/miniconda/envs/scikit-bio/lib/python3.5/site-packages/numpy/testing/utils.py", line 892, in assert_array_almost_equal
    precision=decimal)
  File "/Users/jairideout/miniconda/envs/scikit-bio/lib/python3.5/site-packages/numpy/testing/utils.py", line 713, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not almost equal to 6 decimals

(mismatch 31.42857142857143%)
 x: array([[ -1.209385e+00,  -9.996717e-01,   2.040803e-01,  -4.377164e-02,
          2.025459e-01,   4.174845e-02,   2.251712e-03],
       [ -1.262748e+00,  -1.114136e+00,   1.333392e-01,  -5.340052e-17,...
 y: array([[ -1.209385e+00,   9.996717e-01,   2.040803e-01,  -4.377164e-02,
         -2.025459e-01,  -4.174845e-02,   2.251712e-03],
       [ -1.262748e+00,   1.114136e+00,   1.333392e-01,  -5.659699e-17,...

======================================================================
FAIL: test_scaling2 (__main__.TestRDAResults)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "skbio/stats/ordination/tests/test_redundancy_analysis.py", line 167, in test_scaling2
    decimal=6)
  File "/Users/jairideout/dev/scikit-bio/skbio/util/_testing.py", line 1035, in assert_ordination_results_equal
    decimal=decimal)
  File "/Users/jairideout/dev/scikit-bio/skbio/util/_testing.py", line 1083, in _assert_frame_equal
    npt.assert_almost_equal(left_values, right_values, decimal=decimal)
  File "/Users/jairideout/miniconda/envs/scikit-bio/lib/python3.5/site-packages/numpy/testing/utils.py", line 497, in assert_almost_equal
    return assert_array_almost_equal(actual, desired, decimal, err_msg)
  File "/Users/jairideout/miniconda/envs/scikit-bio/lib/python3.5/site-packages/numpy/testing/utils.py", line 892, in assert_array_almost_equal
    precision=decimal)
  File "/Users/jairideout/miniconda/envs/scikit-bio/lib/python3.5/site-packages/numpy/testing/utils.py", line 713, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not almost equal to 6 decimals

(mismatch 31.42857142857143%)
 x: array([[ -1.488490e+00,  -2.126756e+00,   7.278053e-01,  -2.272346e-01,
          3.841304e+00,   2.304877e+00,   2.600617e-01],
       [ -1.554168e+00,  -2.370273e+00,   4.755236e-01,  -2.772216e-16,...
 y: array([[ -1.488490e+00,   2.126756e+00,   7.278053e-01,  -2.272346e-01,
         -3.841304e+00,  -2.304877e+00,   2.600617e-01],
       [ -1.554168e+00,   2.370273e+00,   4.755236e-01,  -2.938157e-16,...

----------------------------------------------------------------------
Ran 3 tests in 0.194s

FAILED (failures=2)
```

Composition:

```shell
$ nosetests --with-doctest skbio/stats/composition.py
........F....
======================================================================
FAIL: Doctest: skbio.stats.composition.inner
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jairideout/miniconda/envs/scikit-bio/lib/python3.5/doctest.py", line 2189, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for skbio.stats.composition.inner
  File "/Users/jairideout/dev/scikit-bio/skbio/stats/composition.py", line 375, in inner

----------------------------------------------------------------------
File "/Users/jairideout/dev/scikit-bio/skbio/stats/composition.py", line 410, in skbio.stats.composition.inner
Failed example:
    inner(x, y)
Expected:
    0.21078524737545556
Got:
    0.21078524737545554


----------------------------------------------------------------------
Ran 13 tests in 0.063s

FAILED (failures=1)
```

The composition doctest failure should be easy to fix with `round`. The test passes with numpy 1.10.2 and fails with 1.10.4.

I'm not sure about the RDA unit test failures -- these values are different even though the tests are using `npt.assert_almost_equal`. Upgrading/downgrading scipy/numpy versions didn't resolve the issue for me as it did for the composition doctest. @Jorge-C are you available to look into the RDA tests?

**Comment by Jorge-C** [comment]
Yep, the issue is pretty simple: the eigendecomposition routines don't guarantee signs (i.e, the answer is correct modulo signs) and they can change between lapack implementations, versions, etc.

There's a testing function that does some smart checks to normalize signs and avoid "stochastic" failures like this one. Thus, either the failing test is not calling the normalizing routine first, or there's another tricky edgecase that it doesn't deal with.

**Comment by Jorge-C** [comment]
Also, I'll send a PR.

**Comment by jairideout** [comment]
Thanks @Jorge-C!
