### ISSUE TITLE
Issue with GZIP IO unit tests in Debian CI

### ISSUE THREAD

**Issue by kdmurray91** [biocore/scikit-bio#1275]
Hi all,

i've added [debian autopkgtests](https://ci.debian.net/) to the skbio packages. in doing so I've noticed some strange test failures.

The output is below. Reproducing this exactly might be a bit of a pain, but if you have docker I can give you a dockerfile that should help.

Cheers,
K

----

## Python 2:
```
======================================================================
FAIL: test_open_gzip (skbio.io.tests.test_util.TestWriteBufferedReader)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/skbio/io/tests/test_util.py", line 337, in test_open_gzip
    self.gzip_contents[10:])
AssertionError: "example_file\x00\x0b\xc9\xc8,V\x00\xa2\xe2\xfc\xdcT\x85\xe4\xfc\xbc\x92\xd4\xbc\x12.\xcf\x12\x85\xfc\xe4\xe4\xd2\xa2b\x85\xfc<\x85\xdc\xfc\xa2T\x85\x92\x8c\xc4< 'U!'3/\x95\x0b\x00\x8a\x9d\xf4\x165\x00\x00\x00" != "\x0b\xc9\xc8,V\x00\xa2\xe2\xfc\xdcT\x85\xe4\xfc\xbc\x92\xd4\xbc\x12.\xcf\x12\x85\xfc\xe4\xe4\xd2\xa2b\x85\xfc<\x85\xdc\xfc\xa2T\x85\x92\x8c\xc4< 'U!'3/\x95\x0b\x00\x8a\x9d\xf4\x165\x00\x00\x00"

======================================================================
FAIL: test_open_gzip_encoding (skbio.io.tests.test_util.TestWriteBufferedReader)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/skbio/io/tests/test_util.py", line 360, in test_open_gzip_encoding
    self.gzip_encoded_contents[10:])
AssertionError: 'big5_file\x00[\xee\xb8,\x8f\x0b\x00&\x05\xd3\xe1\x05\x00\x00\x00' != '[\xee\xb8,\x8f\x0b\x00&\x05\xd3\xe1\x05\x00\x00\x00'

======================================================================
FAIL: test_open_gzip (skbio.io.tests.test_util.TestWriteBytesIO)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/skbio/io/tests/test_util.py", line 487, in test_open_gzip
    self.gzip_contents[23:])
AssertionError: "\x0b\xc9\xc8,V\x00\xa2\xe2\xfc\xdcT\x85\xe4\xfc\xbc\x92\xd4\xbc\x12.\xcf\x12\x85\xfc\xe4\xe4\xd2\xa2b\x85\xfc<\x85\xdc\xfc\xa2T\x85\x92\x8c\xc4< 'U!'3/\x95\x0b\x00\x8a\x9d\xf4\x165\x00\x00\x00" != "\xfc\xbc\x92\xd4\xbc\x12.\xcf\x12\x85\xfc\xe4\xe4\xd2\xa2b\x85\xfc<\x85\xdc\xfc\xa2T\x85\x92\x8c\xc4< 'U!'3/\x95\x0b\x00\x8a\x9d\xf4\x165\x00\x00\x00"

======================================================================
FAIL: test_open_gzip_encoding (skbio.io.tests.test_util.TestWriteBytesIO)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/skbio/io/tests/test_util.py", line 496, in test_open_gzip_encoding
    self.gzip_encoded_contents[20:])
AssertionError: '[\xee\xb8,\x8f\x0b\x00&\x05\xd3\xe1\x05\x00\x00\x00' != '\xe1\x05\x00\x00\x00'

======================================================================
FAIL: test_open_gzip (skbio.io.tests.test_util.TestWriteFilepath)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/skbio/io/tests/test_util.py", line 337, in test_open_gzip
    self.gzip_contents[10:])
AssertionError: "example_file\x00\x0b\xc9\xc8,V\x00\xa2\xe2\xfc\xdcT\x85\xe4\xfc\xbc\x92\xd4\xbc\x12.\xcf\x12\x85\xfc\xe4\xe4\xd2\xa2b\x85\xfc<\x85\xdc\xfc\xa2T\x85\x92\x8c\xc4< 'U!'3/\x95\x0b\x00\x8a\x9d\xf4\x165\x00\x00\x00" != "\x0b\xc9\xc8,V\x00\xa2\xe2\xfc\xdcT\x85\xe4\xfc\xbc\x92\xd4\xbc\x12.\xcf\x12\x85\xfc\xe4\xe4\xd2\xa2b\x85\xfc<\x85\xdc\xfc\xa2T\x85\x92\x8c\xc4< 'U!'3/\x95\x0b\x00\x8a\x9d\xf4\x165\x00\x00\x00"

======================================================================
FAIL: test_open_gzip_encoding (skbio.io.tests.test_util.TestWriteFilepath)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/skbio/io/tests/test_util.py", line 360, in test_open_gzip_encoding
    self.gzip_encoded_contents[10:])
AssertionError: 'big5_file\x00[\xee\xb8,\x8f\x0b\x00&\x05\xd3\xe1\x05\x00\x00\x00' != '[\xee\xb8,\x8f\x0b\x00&\x05\xd3\xe1\x05\x00\x00\x00'

----------------------------------------------------------------------
Ran 1790 tests in 55.480s

FAILED (SKIP=1, failures=6)
```

## Python 3
(looks superficially the same to me, but here it is anyway)

```
======================================================================
FAIL: test_open_gzip (skbio.io.tests.test_util.TestWriteBufferedReader)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/skbio/io/tests/test_util.py", line 337, in test_open_gzip
    self.gzip_contents[10:])
AssertionError: b"example_file\x00\x0b\xc9\xc8,V\x00\xa2\xe[163 chars]\x00" != b"\x0b\xc9\xc8,V\x00\xa2\xe2\xfc\xdcT\x85\x[147 chars]\x00"

======================================================================
FAIL: test_open_gzip_encoding (skbio.io.tests.test_util.TestWriteBufferedReader)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/skbio/io/tests/test_util.py", line 360, in test_open_gzip_encoding
    self.gzip_encoded_contents[10:])
AssertionError: b'big5_file\x00[\xee\xb8,\x8f\x0b\x00&\x05\xd3\xe1\x05\x00\x00\x00' != b'[\xee\xb8,\x8f\x0b\x00&\x05\xd3\xe1\x05\x00\x00\x00'

======================================================================
FAIL: test_open_gzip (skbio.io.tests.test_util.TestWriteBytesIO)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/skbio/io/tests/test_util.py", line 487, in test_open_gzip
    self.gzip_contents[23:])
AssertionError: b"\x0b\xc9\xc8,V\x00\xa2\xe2\xfc\xdcT\x85\xe4[145 chars]\x00" != b"\xfc\xbc\x92\xd4\xbc\x12.\xcf\x12\x85\xfc\x[102 chars]\x00"

======================================================================
FAIL: test_open_gzip_encoding (skbio.io.tests.test_util.TestWriteBytesIO)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/skbio/io/tests/test_util.py", line 496, in test_open_gzip_encoding
    self.gzip_encoded_contents[20:])
AssertionError: b'[\xee\xb8,\x8f\x0b\x00&\x05\xd3\xe1\x05\x00\x00\x00' != b'\xe1\x05\x00\x00\x00'

======================================================================
FAIL: test_open_gzip (skbio.io.tests.test_util.TestWriteFilepath)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/skbio/io/tests/test_util.py", line 337, in test_open_gzip
    self.gzip_contents[10:])
AssertionError: b"example_file\x00\x0b\xc9\xc8,V\x00\xa2\xe[163 chars]\x00" != b"\x0b\xc9\xc8,V\x00\xa2\xe2\xfc\xdcT\x85\x[147 chars]\x00"

======================================================================
FAIL: test_open_gzip_encoding (skbio.io.tests.test_util.TestWriteFilepath)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/skbio/io/tests/test_util.py", line 360, in test_open_gzip_encoding
    self.gzip_encoded_contents[10:])
AssertionError: b'big5_file\x00[\xee\xb8,\x8f\x0b\x00&\x05\xd3\xe1\x05\x00\x00\x00' != b'[\xee\xb8,\x8f\x0b\x00&\x05\xd3\xe1\x05\x00\x00\x00'

----------------------------------------------------------------------
Ran 1999 tests in 67.198s

FAILED (failures=6)
```

**Comment by Jorge-C** [comment]
I'd be happy to look at reproducing this. Can you point us to the dockerfile? Thanks!

**Comment by kdmurray91** [comment]
I can, however I realised that you'll need to use the development version of the skbio debian package that has a few patches to the tests to make things work.

**Comment by ebolyen** [comment]
@kdmurray91 given that these tests are all gzip related, I would hazard a guess that it has to do with timestamp. gzip sticks the timestamp at the front of the file, if that isn't there (probably the case) or is different somehow (?), then the "offset" that the tests use will be different. All of the gzip tests skip the first 10 bytes which are volatile, but this probably doesn't hold in all situations. Not sure how we would robustly handle this.

**Comment by kdmurray91** [comment]
So it turns out this is going to be a right pain in the butt for you guys to reproduce, as I can only get it to happen inside the build environment (I think). Is there anything I can do locally that can help test your theory @ebolyen? Or should I just make a Docker image that sets up the build environment? Or do one of you run Debian?

**Comment by ebolyen** [comment]
I run Ubuntu, how Debian-y does it need to be to reproduce? 

Also, I think I have an idea for how to fix it: instead of skipping bytes, we just read so many from the back of the file. Then it doesn't matter what gzip does to the front of the file. If we can't reproduce it locally, would you be willing to try that on some of the failing tests to see if that fixes the problem?

**Comment by kdmurray91** [comment]
Well you need to be able to pull packages from debian unstable and set up a git pbuilder, so actual Debian levels of Debian are required :smile:.

Luckily I'm running debian unstable here, so if you can give me a patch (or branch or whatever) implementing the above it's pretty easy for me to test it.

**Comment by jairideout** [comment]
Thanks @kdmurray91! I think we should be able to just compare the last 8 bytes of the file since that includes the checksum and uncompressed data length. I'll get those changes pushed to a branch so you can test.

**Comment by jairideout** [comment]
@kdmurray91 the potential fix I described is on my fork's `issue-1275` branch: https://github.com/jairideout/scikit-bio/tree/issue-1275

Is this sufficient for you to be able to test locally?

**Comment by kdmurray91** [comment]
Yep, that's perfect. Testing now

**Comment by kdmurray91** [comment]
@jairideout can confirm your fix works! Thanks for the fast debugging.

Out of interest, when are you likely to do the 0.4.2 release? If this is in the next few days I'll hold off on the debian release till then, otherwise I'll upload today.

**Comment by jairideout** [comment]
Great, glad to hear that fixed it! Thanks for testing locally. I'll submit a PR to get the fix in scikit-bio.

We're planning on releasing 0.4.2 tomorrow. If you notice anything else in the meantime, please let us know and we'll do our best to fix it for the release. I had one release-related question [here](https://github.com/biocore/scikit-bio/issues/1256#issuecomment-184911155) that might be good to iron out before the actual release.

Thanks again!
