### ISSUE TITLE
Conda build requires a higher version of `libc` than is ideal

### ISSUE THREAD

**Issue by ebolyen** [biocore/scikit-bio#1392]
Discovered by @wasade 
```bash
$ uname -a
Linux barnacle.ucsd.edu 2.6.32-504.23.4.el6.x86_64 #1 SMP Tue Jun 9 20:57:37 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/redhat-release
CentOS release 6.6 (Final)
$ conda create --name skbio-dev python=3
$ source activate skbio-dev
$ conda install -y -c https://conda.anaconda.org/biocore scikit-bio
$ python -c "import skbio"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/mcdonadt/miniconda3/envs/skbio-dev/lib/python3.5/site-packages/skbio/__init__.py", line 13, in <module>
    import skbio.io  # noqa
  File "/home/mcdonadt/miniconda3/envs/skbio-dev/lib/python3.5/site-packages/skbio/io/__init__.py", line 234, in <module>
    import_module('skbio.io.format.clustal')
  File "/home/mcdonadt/miniconda3/envs/skbio-dev/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/mcdonadt/miniconda3/envs/skbio-dev/lib/python3.5/site-packages/skbio/io/format/clustal.py", line 148, in <module>
    from skbio.alignment import TabularMSA
  File "/home/mcdonadt/miniconda3/envs/skbio-dev/lib/python3.5/site-packages/skbio/alignment/__init__.py", line 206, in <module>
    from ._pairwise import (
  File "/home/mcdonadt/miniconda3/envs/skbio-dev/lib/python3.5/site-packages/skbio/alignment/_pairwise.py", line 15, in <module>
    from skbio.alignment._ssw_wrapper import StripedSmithWaterman
ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/mcdonadt/miniconda3/envs/skbio-dev/lib/python3.5/site-packages/skbio/alignment/_ssw_wrapper.cpython-35m-x86_64-linux-gnu.so)
```

It isn't clear if there is a good way to differentiate, but based on [this](https://groups.google.com/a/continuum.io/forum/#!topic/conda/_MGxU8vOBPw) thread, it looks like some people just compile on older/stabler distros as more upstream distros are typically backwards compatible.

Installing from source worked fine, so this isn't critical, but it would be nice to have especially if we were to automate releases/builds.

**Comment by jairideout** [comment]
Bumping the severity of this issue as a conda install of scikit-bio on the Knight lab cluster doesn't work, which also affects a QIIME 2 install on that system.

For those having this issue, the workaround is to uninstall scikit-bio from conda and install it with pip:

```bash
conda uninstall scikit-bio
pip install scikit-bio
```

**Comment by ebolyen** [comment]
@wasade it looks like scikit-bio 0.5.0 has made it into the main `anaconda` channel. If you have time at some point would you mind checking to see if `libc` is still an issue for that particular build?

**Comment by wasade** [comment]
Looks good:

```bash
(bp)09:38:13 (dtmcdonald@barnacle):improved-octo-waddle@master$ conda create --name skbio-
test python=3
Fetching package metadata: ....
Solving package specifications: .........
Package plan for installation in environment /home/mcdonadt/miniconda3/envs/skbio-test:

The following NEW packages will be INSTALLED:

    openssl:    1.0.2h-1
    pip:        8.1.2-py35_0
    python:     3.5.2-0
    readline:   6.2-2
    setuptools: 23.0.0-py35_0
    sqlite:     3.13.0-0
    tk:         8.5.18-0
    wheel:      0.29.0-py35_0
    xz:         5.2.2-0
    zlib:       1.2.8-3

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ]|#############################################################| 100%
#
# To activate this environment, use:
# $ source activate skbio-test
#
# To deactivate this environment, use:
# $ source deactivate
#
(bp)09:38:41 (dtmcdonald@barnacle):improved-octo-waddle@master$ act skbio-test
discarding /home/mcdonadt/miniconda3/envs/bp/bin from PATH
prepending /home/mcdonadt/miniconda3/envs/skbio-test/bin to PATH
(skbio-test)09:38:45 (dtmcdonald@barnacle):improved-octo-waddle@master$ cd ..
(skbio-test)09:38:46 (dtmcdonald@barnacle):~$ conda install scikit-bio
Fetching package metadata: ....
Solving package specifications: .
Package plan for installation in environment /home/mcdonadt/miniconda3/envs/skbio-test:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pango-1.39.0               |                1         668 KB
    natsort-5.0.1              |           py35_0          43 KB
    scipy-0.18.0               |      np111py35_0        30.5 MB
    traitlets-4.2.2            |           py35_0         113 KB
    scikit-bio-0.5.0           |      np111py35_0         1.2 MB
    ------------------------------------------------------------
                                           Total:        32.5 MB

The following NEW packages will be INSTALLED:

    cachecontrol:     0.11.6-py35_0
    cairo:            1.12.18-6
    cycler:           0.10.0-py35_0
    decorator:        4.0.10-py35_0
    fontconfig:       2.11.1-6
    freetype:         2.5.5-1
    glib:             2.43.0-1
    harfbuzz:         0.9.39-1
    ipython:          5.0.0-py35_0
    ipython_genutils: 0.1.0-py35_0
    libffi:           3.2.1-0
    libgfortran:      3.0.0-1
    libpng:           1.6.22-0
    libxml2:          2.9.2-0
    lockfile:         0.12.2-py35_0
    matplotlib:       1.5.1-np111py35_0
    mkl:              11.3.3-0
    natsort:          5.0.1-py35_0
    nose:             1.3.7-py35_1
    numpy:            1.11.1-py35_0
    pandas:           0.18.1-np111py35_0
    pango:            1.39.0-1
    path.py:          8.2.1-py35_0
    pexpect:          4.0.1-py35_0
    pickleshare:      0.7.2-py35_0
    pixman:           0.32.6-0
    prompt_toolkit:   1.0.3-py35_0
    ptyprocess:       0.5.1-py35_0
    pygments:         2.1.3-py35_0
    pyparsing:        2.1.4-py35_0
    pyqt:             4.11.4-py35_4
    python-dateutil:  2.5.3-py35_0
    pytz:             2016.6.1-py35_0
    qt:               4.8.7-4
    requests:         2.10.0-py35_0
    scikit-bio:       0.5.0-np111py35_0
    scipy:            0.18.0-np111py35_0
    simplegeneric:    0.8.1-py35_1
    sip:              4.18-py35_0
    six:              1.10.0-py35_0
    traitlets:        4.2.2-py35_0
    wcwidth:          0.1.7-py35_0

Proceed ([y]/n)? y

Fetching packages ...
pango-1.39.0-1 100% |##########################################| Time: 0:00:00 898.85 kB/s
natsort-5.0.1- 100% |##########################################| Time: 0:00:00 314.63 kB/s
scipy-0.18.0-n 100% |##########################################| Time: 0:00:03   8.81 MB/s
traitlets-4.2. 100% |##########################################| Time: 0:00:00 415.80 kB/s
scikit-bio-0.5 100% |##########################################| Time: 0:00:01   1.16 MB/s
Extracting packages ...
[      COMPLETE      ]|#############################################################| 100%
Linking packages ...
[      COMPLETE      ]|#############################################################| 100%
(skbio-test)09:40:40 (dtmcdonald@barnacle):~$ python -c "import skbio"
(skbio-test)09:40:51 (dtmcdonald@barnacle):~$
```
