### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by wasade** [biocore/scikit-bio#1403]
I was running through the QIIME2 quick start, and encountered the following issue. I wasn't sure if this should be opened on QIIME2's tracker, but since the issue surrounds a scikit-bio dependency, I thought it best to put here

```bash
(bp)11:34:03 (mcdonadt@Daniels-MacBook-Pro):~$ conda create -n q2test -c qiime2 python=3.5 qiime q2cli
Fetching package metadata: ......
Solving package specifications: .........

Package plan for installation in environment /Users/mcdonadt/miniconda3/envs/q2test:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    python-3.5.2               |                0        12.6 MB
    numpy-1.11.1               |           py35_0         2.7 MB
    pytz-2016.6.1              |           py35_0         176 KB
    pyyaml-3.11                |           py35_4         130 KB
    sip-4.18                   |           py35_0         219 KB
    wcwidth-0.1.7              |           py35_0          21 KB
    prompt_toolkit-1.0.3       |           py35_0         308 KB
    qt-4.8.7                   |                4        37.1 MB
    ipython-5.0.0              |           py35_0         990 KB
    pyqt-4.11.4                |           py35_4         4.0 MB
    jupyter_console-5.0.0      |           py35_0          29 KB
    qiime-2.0.1                |           py35_0         183 KB
    q2cli-0.0.1                |           py35_0          15 KB
    ------------------------------------------------------------
                                           Total:        58.4 MB

The following NEW packages will be INSTALLED:

    appnope:          0.1.0-py35_0
    click:            6.6-py35_0
    decorator:        4.0.10-py35_0
    entrypoints:      0.2.2-py35_0
    freetype:         2.5.5-1
    ipykernel:        4.3.1-py35_0
    ipython:          5.0.0-py35_0
    ipython_genutils: 0.1.0-py35_0
    ipywidgets:       4.1.1-py35_0
    jinja2:           2.8-py35_1
    jsonschema:       2.5.1-py35_0
    jupyter:          1.0.0-py35_3
    jupyter_client:   4.3.0-py35_0
    jupyter_console:  5.0.0-py35_0
    jupyter_core:     4.1.0-py35_0
    libpng:           1.6.22-0
    markupsafe:       0.23-py35_2
    mistune:          0.7.2-py35_1
    mkl:              11.3.3-0
    nbconvert:        4.2.0-py35_0
    nbformat:         4.0.1-py35_0
    notebook:         4.2.1-py35_0
    numpy:            1.11.1-py35_0
    openssl:          1.0.2h-1
    pandas:           0.18.1-np111py35_0
    path.py:          8.2.1-py35_0
    pexpect:          4.0.1-py35_0
    pickleshare:      0.7.2-py35_0
    pip:              8.1.2-py35_0
    prompt_toolkit:   1.0.3-py35_0
    ptyprocess:       0.5.1-py35_0
    pygments:         2.1.3-py35_0
    pyqt:             4.11.4-py35_4
    python:           3.5.2-0
    python-dateutil:  2.5.3-py35_0
    python.app:       1.2-py35_4
    pytz:             2016.6.1-py35_0
    pyyaml:           3.11-py35_4
    pyzmq:            15.2.0-py35_1
    q2cli:            0.0.1-py35_0
    qiime:            2.0.1-py35_0
    qt:               4.8.7-4
    qtconsole:        4.2.1-py35_0
    readline:         6.2-2
    setuptools:       23.0.0-py35_0
    simplegeneric:    0.8.1-py35_1
    sip:              4.18-py35_0
    six:              1.10.0-py35_0
    sqlite:           3.13.0-0
    terminado:        0.6-py35_0
    tk:               8.5.18-0
    tornado:          4.3-py35_1
    traitlets:        4.2.1-py35_0
    wcwidth:          0.1.7-py35_0
    wheel:            0.29.0-py35_0
    xz:               5.2.2-0
    yaml:             0.1.6-0
    zlib:             1.2.8-3

Proceed ([y]/n)? y

Fetching packages ...
python-3.5.2-0 100% |##########################################################################################| Time: 0:01:25 154.22 kB/s
numpy-1.11.1-p 100% |##########################################################################################| Time: 0:00:22 127.18 kB/s
pytz-2016.6.1- 100% |##########################################################################################| Time: 0:00:01 161.20 kB/s
pyyaml-3.11-py 100% |##########################################################################################| Time: 0:00:00 207.85 kB/s
sip-4.18-py35_ 100% |##########################################################################################| Time: 0:00:01 159.96 kB/s
wcwidth-0.1.7- 100% |##########################################################################################| Time: 0:00:00 172.79 kB/s
prompt_toolkit 100% |##########################################################################################| Time: 0:00:01 182.48 kB/s
qt-4.8.7-4.tar 100% |##########################################################################################| Time: 0:05:16 122.99 kB/s
ipython-5.0.0- 100% |##########################################################################################| Time: 0:00:07 141.21 kB/s
pyqt-4.11.4-py 100% |##########################################################################################| Time: 0:00:32 127.66 kB/s
jupyter_consol 100% |##########################################################################################| Time: 0:00:00 197.68 kB/s
qiime-2.0.1-py 100% |##########################################################################################| Time: 0:00:00 285.24 kB/s
q2cli-0.0.1-py 100% |##########################################################################################| Time: 0:00:00 326.57 kB/s
Extracting packages ...
[      COMPLETE      ]|#############################################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|#############################################################################################################| 100%
#
# To activate this environment, use:
# $ source activate q2test
#
# To deactivate this environment, use:
# $ source deactivate
#
(bp)11:43:14 (mcdonadt@Daniels-MacBook-Pro):~$ source activate q2test
(q2test)11:57:53 (mcdonadt@Daniels-MacBook-Pro):~$ conda install -c qiime2 -c biocore -c bioconda q2-types q2-feature-table
Fetching package metadata: ..........
Solving package specifications: .........

Package plan for installation in environment /Users/mcdonadt/miniconda3/envs/q2test:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    scipy-0.17.1               |      np111py35_1        11.9 MB
    q2-types-0.0.1             |           py35_0          33 KB
    q2-feature-table-0.0.1     |           py35_0          15 KB
    ------------------------------------------------------------
                                           Total:        11.9 MB

The following NEW packages will be INSTALLED:

    biom-format:      2.1.5-py35_3
    cachecontrol:     0.11.6-py35_0
    cycler:           0.10.0-py35_0
    future:           0.15.2-py35_0
    h5py:             2.6.0-np111py35_1
    hdf5:             1.8.16-0
    lockfile:         0.12.2-py35_0
    matplotlib:       1.5.1-np111py35_0
    natsort:          4.0.3-py35_0
    nose:             1.3.7-py35_1
    pyparsing:        2.1.4-py35_0
    q2-feature-table: 0.0.1-py35_0
    q2-types:         0.0.1-py35_0
    requests:         2.10.0-py35_0
    scikit-bio:       0.5.0-py35_0
    scipy:            0.17.1-np111py35_1
    seaborn:          0.7.0-py35_0

Proceed ([y]/n)? y

Fetching packages ...
scipy-0.17.1-n 100% |##########################################################################################| Time: 0:01:31 136.69 kB/s
q2-types-0.0.1 100% |##########################################################################################| Time: 0:00:00 213.87 kB/s
q2-feature-tab 100% |##########################################################################################| Time: 0:00:00 148.07 kB/s
Extracting packages ...
[      COMPLETE      ]|#############################################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|#############################################################################################################| 100%
(q2test)11:59:37 (mcdonadt@Daniels-MacBook-Pro):~$ qiime info
Traceback (most recent call last):
  File "/Users/mcdonadt/miniconda3/envs/q2test/bin/qiime", line 4, in <module>
    import q2cli.cli
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/Users/mcdonadt/miniconda3/envs/q2test/lib/python3.5/site-packages/q2cli-0.0.1-py3.5.egg/q2cli/cli.py", line 22, in <module>
  File "/Users/mcdonadt/miniconda3/envs/q2test/lib/python3.5/site-packages/q2cli-0.0.1-py3.5.egg/q2cli/cli.py", line 24, in QiimeCLI
  File "/Users/mcdonadt/miniconda3/envs/q2test/lib/python3.5/site-packages/qiime-2.0.1-py3.5.egg/qiime/sdk/plugin_manager.py", line 21, in __new__
    self._init()
  File "/Users/mcdonadt/miniconda3/envs/q2test/lib/python3.5/site-packages/qiime-2.0.1-py3.5.egg/qiime/sdk/plugin_manager.py", line 35, in _init
    plugins.append(entry_point.load())
  File "/Users/mcdonadt/miniconda3/envs/q2test/lib/python3.5/site-packages/setuptools-23.0.0-py3.5.egg/pkg_resources/__init__.py", line 2228, in load
  File "/Users/mcdonadt/miniconda3/envs/q2test/lib/python3.5/site-packages/setuptools-23.0.0-py3.5.egg/pkg_resources/__init__.py", line 2245, in require
  File "/Users/mcdonadt/miniconda3/envs/q2test/lib/python3.5/site-packages/setuptools-23.0.0-py3.5.egg/pkg_resources/__init__.py", line 829, in resolve
pkg_resources.DistributionNotFound: The 'contextlib2>=0.4.0' distribution was not found and is required by scikit-bio
```

**Comment by wasade** [comment]
...I just `conda install contextlib2`, and reran the qiime2 command, and received the following:

```bash
(q2test)12:07:18 (mcdonadt@Daniels-MacBook-Pro):~$ qiime info
Traceback (most recent call last):
  File "/Users/mcdonadt/miniconda3/envs/q2test/bin/qiime", line 4, in <module>
    import q2cli.cli
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/Users/mcdonadt/miniconda3/envs/q2test/lib/python3.5/site-packages/q2cli-0.0.1-py3.5.egg/q2cli/cli.py", line 22, in <module>
  File "/Users/mcdonadt/miniconda3/envs/q2test/lib/python3.5/site-packages/q2cli-0.0.1-py3.5.egg/q2cli/cli.py", line 24, in QiimeCLI
  File "/Users/mcdonadt/miniconda3/envs/q2test/lib/python3.5/site-packages/qiime-2.0.1-py3.5.egg/qiime/sdk/plugin_manager.py", line 21, in __new__
    self._init()
  File "/Users/mcdonadt/miniconda3/envs/q2test/lib/python3.5/site-packages/qiime-2.0.1-py3.5.egg/qiime/sdk/plugin_manager.py", line 35, in _init
    plugins.append(entry_point.load())
  File "/Users/mcdonadt/miniconda3/envs/q2test/lib/python3.5/site-packages/setuptools-23.0.0-py3.5.egg/pkg_resources/__init__.py", line 2228, in load
  File "/Users/mcdonadt/miniconda3/envs/q2test/lib/python3.5/site-packages/setuptools-23.0.0-py3.5.egg/pkg_resources/__init__.py", line 2245, in require
  File "/Users/mcdonadt/miniconda3/envs/q2test/lib/python3.5/site-packages/setuptools-23.0.0-py3.5.egg/pkg_resources/__init__.py", line 829, in resolve
pkg_resources.DistributionNotFound: The 'bz2file>=0.98' distribution was not found and is required by scikit-bio
```

**Comment by gregcaporaso** [comment]
@wasade, @jairideout and I just tried the same command and it's not failing for us. We're still trying to see if we can reproduce it, more soon.

**Comment by wasade** [comment]
Weird, okay, thanks. I'll rerun on a separate system too.

**Comment by gregcaporaso** [comment]
Could you also try:

```bash
conda install scikit-bio -c biocore
```

and then try to import ``skbio`` and let us know if that's working?

**Comment by wasade** [comment]
I already modified the environment by installing contextlib2 and bz2file manually. Will destroy and attempt again.

**Comment by wasade** [comment]
Different issue now, from barnacle:

```bash
(py34-base)12:35:33 (dtmcdonald@barnacle):~$ conda create -n q2test -c qiime2 python=3.5 qiime q2cli
Fetching package metadata: ......
Solving package specifications: .........................
Package plan for installation in environment /home/mcdonadt/miniconda3/envs/q2test:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libffi-3.2.1               |                0          36 KB
    libsodium-1.0.10           |                0         1.2 MB
    xz-5.2.2                   |                0         644 KB
    yaml-0.1.6                 |                0         246 KB
    glib-2.43.0                |                1         5.4 MB
    libpng-1.6.22              |                0         214 KB
    zeromq-4.1.4               |                0         4.1 MB
    fontconfig-2.11.1          |                6         405 KB
    harfbuzz-0.9.39            |                1         1.1 MB
    pango-1.39.0               |                0         777 KB
    qt-4.8.7                   |                4        32.7 MB
    entrypoints-0.2.2          |           py35_0           6 KB
    jsonschema-2.5.1           |           py35_0          56 KB
    markupsafe-0.23            |           py35_2          32 KB
    mistune-0.7.2              |           py35_0         662 KB
    numpy-1.11.1               |           py35_0         6.1 MB
    pygments-2.1.3             |           py35_0         1.2 MB
    python-3.5.2               |                0        17.2 MB
    pytz-2016.6.1              |           py35_0         177 KB
    pyyaml-3.11                |           py35_4         326 KB
    pyzmq-15.2.0               |           py35_1         792 KB
    sip-4.18                   |           py35_0         240 KB
    tornado-4.3                |           py35_1         584 KB
    wcwidth-0.1.7              |           py35_0          21 KB
    jinja2-2.8                 |           py35_1         302 KB
    jupyter_core-4.1.0         |           py35_0          51 KB
    prompt_toolkit-1.0.3       |           py35_0         308 KB
    pyqt-4.11.4                |           py35_4         3.3 MB
    terminado-0.6              |           py35_0          18 KB
    ipython-5.0.0              |           py35_0         989 KB
    jupyter_client-4.3.0       |           py35_0          99 KB
    nbformat-4.0.1             |           py35_0         113 KB
    ipykernel-4.3.1            |           py35_0         120 KB
    nbconvert-4.2.0            |           py35_0         315 KB
    jupyter_console-5.0.0      |           py35_0          29 KB
    notebook-4.2.1             |           py35_0         5.0 MB
    qtconsole-4.2.1            |           py35_0         163 KB
    ipywidgets-4.1.1           |           py35_0          99 KB
    jupyter-1.0.0              |           py35_3           3 KB
    qiime-2.0.1                |           py35_0         180 KB
    q2cli-0.0.1                |           py35_0          14 KB
    ------------------------------------------------------------
                                           Total:        85.0 MB

The following NEW packages will be INSTALLED:

    cairo:            1.12.18-6
    click:            6.6-py35_0
    decorator:        4.0.10-py35_0
    entrypoints:      0.2.2-py35_0
    fontconfig:       2.11.1-6
    freetype:         2.5.5-1
    glib:             2.43.0-1
    harfbuzz:         0.9.39-1
    ipykernel:        4.3.1-py35_0
    ipython:          5.0.0-py35_0
    ipython_genutils: 0.1.0-py35_0
    ipywidgets:       4.1.1-py35_0
    jinja2:           2.8-py35_1
    jsonschema:       2.5.1-py35_0
    jupyter:          1.0.0-py35_3
    jupyter_client:   4.3.0-py35_0
    jupyter_console:  5.0.0-py35_0
    jupyter_core:     4.1.0-py35_0
    libffi:           3.2.1-0
    libpng:           1.6.22-0
    libsodium:        1.0.10-0
    libxml2:          2.9.2-0
    markupsafe:       0.23-py35_2
    mistune:          0.7.2-py35_0
    mkl:              11.3.3-0
    nbconvert:        4.2.0-py35_0
    nbformat:         4.0.1-py35_0
    notebook:         4.2.1-py35_0
    numpy:            1.11.1-py35_0
    openssl:          1.0.2h-1
    pandas:           0.18.1-np111py35_0
    pango:            1.39.0-0
    path.py:          8.2.1-py35_0
    pexpect:          4.0.1-py35_0
    pickleshare:      0.7.2-py35_0
    pip:              8.1.2-py35_0
    pixman:           0.32.6-0
    prompt_toolkit:   1.0.3-py35_0
    ptyprocess:       0.5.1-py35_0
    pygments:         2.1.3-py35_0
    pyqt:             4.11.4-py35_4
    python:           3.5.2-0
    python-dateutil:  2.5.3-py35_0
    pytz:             2016.6.1-py35_0
    pyyaml:           3.11-py35_4
    pyzmq:            15.2.0-py35_1
    q2cli:            0.0.1-py35_0
    qiime:            2.0.1-py35_0
    qt:               4.8.7-4
    qtconsole:        4.2.1-py35_0
    readline:         6.2-2
    setuptools:       23.0.0-py35_0
    simplegeneric:    0.8.1-py35_1
    sip:              4.18-py35_0
    six:              1.10.0-py35_0
    sqlite:           3.13.0-0
    terminado:        0.6-py35_0
    tk:               8.5.18-0
    tornado:          4.3-py35_1
    traitlets:        4.2.1-py35_0
    wcwidth:          0.1.7-py35_0
    wheel:            0.29.0-py35_0
    xz:               5.2.2-0
    yaml:             0.1.6-0
    zeromq:           4.1.4-0
    zlib:             1.2.8-3

Proceed ([y]/n)? y

Fetching packages ...
libffi-3.2.1-0 100% |##########################################| Time: 0:00:00 268.56 kB/s
libsodium-1.0. 100% |##########################################| Time: 0:00:00   1.29 MB/s
xz-5.2.2-0.tar 100% |##########################################| Time: 0:00:00 681.03 kB/s
yaml-0.1.6-0.t 100% |##########################################| Time: 0:00:00 519.68 kB/s
glib-2.43.0-1. 100% |##########################################| Time: 0:00:02   2.75 MB/s
libpng-1.6.22- 100% |##########################################| Time: 0:00:00 454.74 kB/s
zeromq-4.1.4-0 100% |##########################################| Time: 0:00:02   2.00 MB/s
fontconfig-2.1 100% |##########################################| Time: 0:00:00 626.38 kB/s
harfbuzz-0.9.3 100% |##########################################| Time: 0:00:01 998.30 kB/s
pango-1.39.0-0 100% |##########################################| Time: 0:00:00 846.54 kB/s
qt-4.8.7-4.tar 100% |##########################################| Time: 0:00:03   9.57 MB/s
entrypoints-0. 100% |##########################################| Time: 0:00:00   1.70 MB/s
jsonschema-2.5 100% |##########################################| Time: 0:00:00 279.29 kB/s
markupsafe-0.2 100% |##########################################| Time: 0:00:00 239.98 kB/s
mistune-0.7.2- 100% |##########################################| Time: 0:00:00 886.46 kB/s
numpy-1.11.1-p 100% |##########################################| Time: 0:00:02   2.93 MB/s
pygments-2.1.3 100% |##########################################| Time: 0:00:00   1.31 MB/s
python-3.5.2-0 100% |##########################################| Time: 0:00:03   5.76 MB/s
pytz-2016.6.1- 100% |##########################################| Time: 0:00:00 436.75 kB/s
pyyaml-3.11-py 100% |##########################################| Time: 0:00:00 481.85 kB/s
pyzmq-15.2.0-p 100% |##########################################| Time: 0:00:01 781.62 kB/s
sip-4.18-py35_ 100% |##########################################| Time: 0:00:00 592.62 kB/s
tornado-4.3-py 100% |##########################################| Time: 0:00:00 618.98 kB/s
wcwidth-0.1.7- 100% |##########################################| Time: 0:00:00 312.15 kB/s
jinja2-2.8-py3 100% |##########################################| Time: 0:00:00 591.80 kB/s
jupyter_core-4 100% |##########################################| Time: 0:00:00 218.69 kB/s
prompt_toolkit 100% |##########################################| Time: 0:00:00 570.49 kB/s
pyqt-4.11.4-py 100% |##########################################| Time: 0:00:01   1.86 MB/s
terminado-0.6- 100% |##########################################| Time: 0:00:00 268.75 kB/s
ipython-5.0.0- 100% |##########################################| Time: 0:00:01 860.56 kB/s
jupyter_client 100% |##########################################| Time: 0:00:00 365.54 kB/s
nbformat-4.0.1 100% |##########################################| Time: 0:00:00 335.69 kB/s
ipykernel-4.3. 100% |##########################################| Time: 0:00:00 356.12 kB/s
nbconvert-4.2. 100% |##########################################| Time: 0:00:00 664.62 kB/s
jupyter_consol 100% |##########################################| Time: 0:00:00 419.30 kB/s
notebook-4.2.1 100% |##########################################| Time: 0:00:01   2.89 MB/s
qtconsole-4.2. 100% |##########################################| Time: 0:00:00 436.00 kB/s
ipywidgets-4.1 100% |##########################################| Time: 0:00:00 367.23 kB/s
jupyter-1.0.0- 100% |##########################################| Time: 0:00:00 872.87 kB/s
qiime-2.0.1-py 100% |##########################################| Time: 0:00:00 385.08 kB/s
q2cli-0.0.1-py 100% |##########################################| Time: 0:00:00 215.02 kB/s
Extracting packages ...
[      COMPLETE      ]|#############################################################| 100%
Linking packages ...
[      COMPLETE      ]|#############################################################| 100%
#
# To activate this environment, use:
# $ source activate q2test
#
# To deactivate this environment, use:
# $ source deactivate
#
(py34-base)12:38:42 (dtmcdonald@barnacle):~$ act q2test
discarding /home/mcdonadt/miniconda3/envs/py34-base/bin from PATH
prepending /home/mcdonadt/miniconda3/envs/q2test/bin to PATH
(q2test)12:38:55 (dtmcdonald@barnacle):~$ qiime info
System versions
Python version: 3.5.2
QIIME version: 2.0.1
q2cli version: 0.0.1

Installed plugins
No plugins are currently installed.
You can browse the official QIIME 2 plugins at: https://github.com/qiime2

To get help with QIIME, visit http://help.qiime.org.
If you use QIIME in any published work, please cite http://www.ncbi.nlm.nih.gov/pubmed/20383131
(q2test)12:39:08 (dtmcdonald@barnacle):~$ conda install -c qiime2 -c biocore -c bioconda q2-types q2-feature-table
Fetching package metadata: ..........
Solving package specifications: ...........................
Package plan for installation in environment /home/mcdonadt/miniconda3/envs/q2test:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    scipy-0.17.1               |      np111py35_1        29.6 MB
    seaborn-0.7.0              |           py35_0         274 KB
    q2-types-0.0.1             |           py35_0          33 KB
    q2-feature-table-0.0.1     |           py35_0          15 KB
    ------------------------------------------------------------
                                           Total:        29.9 MB

The following NEW packages will be INSTALLED:

    biom-format:      2.1.5-py35_3
    cachecontrol:     0.11.6-py35_0
    cycler:           0.10.0-py35_0
    future:           0.15.2-py35_0
    h5py:             2.6.0-np111py35_1
    hdf5:             1.8.16-0
    libgfortran:      3.0.0-1
    lockfile:         0.12.2-py35_0
    matplotlib:       1.5.1-np111py35_0
    natsort:          4.0.3-py35_0
    nose:             1.3.7-py35_1
    pyparsing:        2.1.4-py35_0
    q2-feature-table: 0.0.1-py35_0
    q2-types:         0.0.1-py35_0
    requests:         2.10.0-py35_0
    scikit-bio:       0.5.0-py35_0
    scipy:            0.17.1-np111py35_1
    seaborn:          0.7.0-py35_0

The following packages will be UPDATED:

    libxml2:          2.9.2-0 --> 2.9.3-0

Proceed ([y]/n)? y

Fetching packages ...
scipy-0.17.1-n 100% |##########################################| Time: 0:00:03   8.17 MB/s
seaborn-0.7.0- 100% |##########################################| Time: 0:00:00 489.65 kB/s
q2-types-0.0.1 100% |##########################################| Time: 0:00:00 246.90 kB/s
q2-feature-tab 100% |##########################################| Time: 0:00:00 221.33 kB/s
Extracting packages ...
[      COMPLETE      ]|#############################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|#############################################################| 100%
Linking packages ...
[      COMPLETE      ]|#############################################################| 100%
(q2test)12:40:34 (dtmcdonald@barnacle):~$ qiime info
Traceback (most recent call last):
  File "/home/mcdonadt/miniconda3/envs/q2test/bin/qiime", line 4, in <module>
    import q2cli.cli
  File "/home/mcdonadt/miniconda3/envs/q2test/lib/python3.5/site-packages/q2cli-0.0.1-py3.5.egg/q2cli/cli.py", line 22, in <module>
  File "/home/mcdonadt/miniconda3/envs/q2test/lib/python3.5/site-packages/q2cli-0.0.1-py3.5.egg/q2cli/cli.py", line 24, in QiimeCLI
  File "/home/mcdonadt/miniconda3/envs/q2test/lib/python3.5/site-packages/qiime-2.0.1-py3.5.egg/qiime/sdk/plugin_manager.py", line 21, in __new__
    self._init()
  File "/home/mcdonadt/miniconda3/envs/q2test/lib/python3.5/site-packages/qiime-2.0.1-py3.5.egg/qiime/sdk/plugin_manager.py", line 35, in _init
    plugins.append(entry_point.load())
  File "/home/mcdonadt/miniconda3/envs/q2test/lib/python3.5/site-packages/setuptools-23.0.0-py3.5.egg/pkg_resources/__init__.py", line 2229, in load
  File "/home/mcdonadt/miniconda3/envs/q2test/lib/python3.5/site-packages/setuptools-23.0.0-py3.5.egg/pkg_resources/__init__.py", line 2235, in resolve
  File "/home/mcdonadt/miniconda3/envs/q2test/lib/python3.5/site-packages/q2_feature_table-0.0.1-py3.5.egg/q2_feature_table/plugin_setup.py", line 12, in <module>
  File "/home/mcdonadt/miniconda3/envs/q2test/lib/python3.5/site-packages/q2_types-0.0.1-py3.5.egg/q2_types/__init__.py", line 11, in <module>
  File "/home/mcdonadt/miniconda3/envs/q2test/lib/python3.5/site-packages/q2_types-0.0.1-py3.5.egg/q2_types/_feature_table.py", line 18, in <module>
  File "/home/mcdonadt/miniconda3/envs/q2test/lib/python3.5/site-packages/q2_types-0.0.1-py3.5.egg/q2_types/plugin_setup.py", line 23, in <module>
  File "/home/mcdonadt/miniconda3/envs/q2test/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/mcdonadt/miniconda3/envs/q2test/lib/python3.5/site-packages/q2_types-0.0.1-py3.5.egg/q2_types/_distance_matrix.py", line 11, in <module>
  File "/home/mcdonadt/miniconda3/envs/q2test/lib/python3.5/site-packages/skbio/__init__.py", line 17, in <module>
    from skbio.alignment import local_pairwise_align_ssw, TabularMSA
ImportError: cannot import name 'local_pairwise_align_ssw'
```

**Comment by wasade** [comment]
A destroy and rebuild of my local laptop environment reproduced the same `contextlib2` issue. @gregcaporaso, your suggestion produced the following:

```bash
$ conda install scikit-bio -c biocore
Fetching package metadata: ......
Solving package specifications: .........

# All requested packages already installed.
# packages in environment at /Users/mcdonadt/miniconda3/envs/q2test:
#
scikit-bio                0.5.0                    py35_0    biocore
```

Conda details below:

```bash
(q2test)12:44:36 (mcdonadt@Daniels-MacBook-Pro):~$ conda info
Current conda install:

             platform : osx-64
        conda version : 4.0.5
  conda-build version : not installed
       python version : 3.5.1.final.0
     requests version : 2.9.1
     root environment : /Users/mcdonadt/miniconda3  (writable)
  default environment : /Users/mcdonadt/miniconda3/envs/q2test
     envs directories : /Users/mcdonadt/miniconda3/envs
        package cache : /Users/mcdonadt/miniconda3/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

**Comment by wasade** [comment]
Had `PYTHONPATH` set, so there was confusion in my environment. Sorry about that. 

Unsure of the barnacle issue though, investigating.

**Comment by jairideout** [comment]
From offline discussion the barnacle issue is #1392. I bumped the severity of that issue and will close this one as it appears to be unrelated to QIIME 2.
