### ISSUE TITLE
Issue in skbio.stats.power code, probably just a broken test?

### ISSUE THREAD

**Issue by ebolyen** [biocore/scikit-bio#1436]
I'm afraid I don't know enough about this code to know if it is just a broken test, or if an update to pandas actually found something interesting. @jwdebelius or @wasade would you be able to investigate? This is blocking #1435.

```pytb
======================================================================
ERROR: test__identify_sample_groups_not_strict (skbio.stats.tests.test_power.PowerAnalysisTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/evan/biocore/scikit-bio/skbio/stats/tests/test_power.py", line 491, in test__identify_sample_groups_not_strict
    sorted(test_pairs.values()))
  File "/home/evan/.conda/envs/skbio/lib/python3.4/site-packages/pandas/indexes/base.py", line 3317, in _evaluate_compare
    raise ValueError('Lengths must match to compare')
ValueError: Lengths must match to compare
```

**Comment by wasade** [comment]
I don't know either here either, sorry

**Comment by RNAer** [comment]
@jwdebelius , is this your code? could you take a look?

**Comment by jwdebelius** [comment]
I'm committed all day tommorrow, but I will go through and follow up over the weekend.

**Comment by jairideout** [comment]
Fixed in https://github.com/biocore/scikit-bio/pull/1439
