### ISSUE TITLE
ValueError: Buffer dtype mismatch in betadiversity

### ISSUE THREAD

**Issue by BLMeltdown** [biocore/scikit-bio#1547]
Hello
I have the following exception when using the following line:

> WU=skbio.diversity.beta_diversity("weighted_unifrac", gen3.values, ids=ids2, tree=st_imp, otu_ids=taxids_n_str)
> Traceback (most recent call last):
> 
>   File "<ipython-input-283-9c4fc7ed72fa>", line 1, in <module>
>     WU=skbio.diversity.beta_diversity("weighted_unifrac", gen3.values, ids=ids2, tree=st_imp, otu_ids=taxids_n_str)
> 
>   File "G:\Anaconda3\lib\site-packages\scikit_bio-0.5.1.dev0-py3.6-win-amd64.egg\skbio\diversity\_driver.py", line 358, in beta_diversity
>     validate=validate)
> 
>   File "G:\Anaconda3\lib\site-packages\scikit_bio-0.5.1.dev0-py3.6-win-amd64.egg\skbio\diversity\beta\_unifrac.py", line 521, in _setup_multiple_weighted_unifrac
>     _setup_multiple_unifrac(counts, otu_ids, tree, validate)
> 
>   File "G:\Anaconda3\lib\site-packages\scikit_bio-0.5.1.dev0-py3.6-win-amd64.egg\skbio\diversity\beta\_unifrac.py", line 452, in _setup_multiple_unifrac
>     _vectorize_counts_and_tree(counts, otu_ids, tree)
> 
>   File "G:\Anaconda3\lib\site-packages\scikit_bio-0.5.1.dev0-py3.6-win-amd64.egg\skbio\diversity\_util.py", line 115, in _vectorize_counts_and_tree
>     counts_by_node = _nodes_by_counts(counts, otu_ids, tree_index)
> 
>   File "skbio/diversity/_phylogenetic.pyx", line 213, in skbio.diversity._phylogenetic._nodes_by_counts (skbio/diversity/_phylogenetic.c:2641)
> 
>   File "skbio/diversity/_phylogenetic.pyx", line 68, in skbio.diversity._phylogenetic._traverse_reduce (skbio/diversity/_phylogenetic.c:1832)
> 
> ValueError: Buffer dtype mismatch, expected 'DTYPE_t' but got 'long'
> 

gen3 has dtype = np.int32 (as set by astype(np.int32),
taxids_n_str =['642', '33877', '1651', '1288026', '544', '204286', '189330', '551', '13075', '2745', '682522', '83654', '445', '1400055', '53', '1004302', '52959', '53246', '1221880', '497', '160674', '75309', '1263', '613', '620', '1569', '82986', '2023', '1649512', '629', '59732', '46913']
(list of strings corresponding to int used to get the tree using the ete3 package and NCBITaxa().get_topology(taxids_n) method (taxids_n being the list of ints version).
ids2 is my list of samples. basically strings too.

I don't understand where the mistake is, as I processed the data the same way than before (the betadiversity method was failing because I hand otu_ids which were not in tree, but at least, that didn't seem to fail because of some type.
Maybe some abundance in gen3 is too big for np.int32 but then the values would not be int32 with gen3.dtypes. I have to use "astype(np.int32)" because else, the function says it 'can't cast array from dtype("np.int64") to dtype("np.int32") according to the rule safe'.
Which is strange is that I am on win64, so it should not fail like this (I built from the current source, v=0.5.1) or try to cast to int32.

**Comment by wasade** [comment]
Hi @BLMeltdown, the input for the fast UniFrac methods in scikit-bio is required to be `int64`, what happens if you do `astype(np.int64)`?
