### ISSUE TITLE
NumPy incompatibility for most recent version during setup.py installation

### ISSUE THREAD

**Issue by jolespin** [biocore/scikit-bio#1636]
I'm trying to install the newest version of `skbio` from `GitHub` but I am having an issue with my `NumPy` version `1.15.3`.  I had some issues with `NumPy v1.15.3` and `numpy-base v1.13.3` so I updated but now have issues updating `skbio`.  Do you have any recommendations to install `skbio v0.5.4` with newer `NumPy` releases? 
```
(∆_env) jespinozlt-osx:install jespinoz$ pip install git+https://github.com/biocore/scikit-bio
Collecting git+https://github.com/biocore/scikit-bio
  Cloning https://github.com/biocore/scikit-bio to /private/var/folders/6z/5vbtz_gmkr76ftgc3149dvtr0003c0/T/pip-req-build-_pj62umd
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/6z/5vbtz_gmkr76ftgc3149dvtr0003c0/T/pip-req-build-_pj62umd/setup.py", line 83, in <module>
        include_dirs=[np.get_include()]),
    AttributeError: module 'numpy' has no attribute 'get_include'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/6z/5vbtz_gmkr76ftgc3149dvtr0003c0/T/pip-req-build-_pj62umd/
```

**Comment by ElDeveloper** [comment]
I pushed the latest version of scikit-bio to pypi and conda-forge earlier today, both packages should be available now. The latest version should work, if that's not the case, please feel free to re-open this issue.
