### ISSUE TITLE
Running help(skbio) produces a TypeError

### ISSUE THREAD

**Issue by fedarko** [biocore/scikit-bio#1656]
Here's a full transcript of the two steps taken to cause this error, along with the resulting stack trace:

```python
Python 3.5.5 | packaged by conda-forge | (default, Apr  6 2018, 13:43:56) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import skbio
>>> help(skbio)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda3/envs/qiime2-2018.8/lib/python3.5/_sitebuiltins.py", line 103, in __call__
    return pydoc.help(*args, **kwds)
  File "/anaconda3/envs/qiime2-2018.8/lib/python3.5/pydoc.py", line 1851, in __call__
    self.help(request)
  File "/anaconda3/envs/qiime2-2018.8/lib/python3.5/pydoc.py", line 1904, in help
    else: doc(request, 'Help on %s:', output=self._output)
  File "/anaconda3/envs/qiime2-2018.8/lib/python3.5/pydoc.py", line 1638, in doc
    pager(render_doc(thing, title, forceload))
  File "/anaconda3/envs/qiime2-2018.8/lib/python3.5/pydoc.py", line 1631, in render_doc
    return title % desc + '\n\n' + renderer.document(object, name)
  File "/anaconda3/envs/qiime2-2018.8/lib/python3.5/pydoc.py", line 375, in document
    if inspect.ismodule(object): return self.docmodule(*args)
  File "/anaconda3/envs/qiime2-2018.8/lib/python3.5/pydoc.py", line 1160, in docmodule
    contents.append(self.document(value, key, name))
  File "/anaconda3/envs/qiime2-2018.8/lib/python3.5/pydoc.py", line 376, in document
    if inspect.isclass(object): return self.docclass(*args)
  File "/anaconda3/envs/qiime2-2018.8/lib/python3.5/pydoc.py", line 1277, in docclass
    for name, kind, cls, value in classify_class_attrs(object)
  File "/anaconda3/envs/qiime2-2018.8/lib/python3.5/pydoc.py", line 206, in classify_class_attrs
    for (name, kind, cls, value) in inspect.classify_class_attrs(object):
  File "/anaconda3/envs/qiime2-2018.8/lib/python3.5/inspect.py", line 402, in classify_class_attrs
    srch_obj = getattr(srch_cls, name, None)
  File "/anaconda3/envs/qiime2-2018.8/lib/python3.5/site-packages/skbio/util/_decorator.py", line 335, in __get__
    return self.fget.__get__(None, owner)()
  File "/anaconda3/envs/qiime2-2018.8/lib/python3.5/site-packages/skbio/sequence/_grammared_sequence.py", line 213, in _definite_char_codes
    [ord(d) for d in definite_chars])
TypeError: 'abstractproperty' object is not iterable
>>>
```

I've reproduced this error multiple times. It occurs in python 3.5, 3.6, and 3.7, and I've reproduced it in both QIIME 2 2018.8 with skbio version 0.5.4 (as shown above) and QIIME 2 2019.1 with skbio version 0.5.5.

In version 0.5.5, the error looks like it's caused by [this particular line of code](https://github.com/biocore/scikit-bio/blob/master/skbio/sequence/_grammared_sequence.py#L201). I'm not that familiar with python's `abc` module, but a bunch of googling about this particular error message led me to [this comment](https://github.com/biocore/scikit-bio/blob/master/doc/source/conf.py#L490), which is also in skbio's code -- it seems like this has been a known issue.

This really isn't that important at all :), but I think fixing it would be a nice usability bonus for anyone who does a lot of messing around in a REPL.

**Comment by ElDeveloper** [comment]
I think @ebolyen might know of a workaround for this, this has 
definitely come up before.
