### ISSUE TITLE
Buffer dtype mismatch in weighted_unifrac

### ISSUE THREAD

**Issue by AaronBlare** [biocore/scikit-bio#1685]
I try to run the example of weighted_unifrac from the docs: http://scikit-bio.org/docs/0.5.5/generated/skbio.diversity.beta.weighted_unifrac.html

```
from io import StringIO
from skbio.tree import TreeNode
from skbio.diversity.beta import unweighted_unifrac

tree = TreeNode.read(StringIO(
    '(((((OTU1:0.5,OTU2:0.5):0.5,OTU3:1.0):1.0):0.0,'
    '(OTU4:0.75,(OTU5:0.5,((OTU6:0.33,OTU7:0.62):0.5'
    ',OTU8:0.5):0.5):0.5):1.25):0.0)root;'))

u_counts = [1, 0, 0, 4, 1, 2, 3, 0]
v_counts = [0, 1, 1, 6, 0, 1, 0, 0]
otu_ids = ['OTU1', 'OTU2', 'OTU3', 'OTU4', 'OTU5', 'OTU6', 'OTU7', 'OTU8']

uu = unweighted_unifrac(u_counts, v_counts, otu_ids, tree)
```

I obtain the following error:

```
Traceback (most recent call last):
  File "D:/test.py", line 14, in <module>
    wu = weighted_unifrac(u_counts, v_counts, otu_ids, tree)
  File "C:\ProgramData\Anaconda3\envs\mtDNA\lib\site-packages\skbio\diversity\beta\_unifrac.py", line 281, in weighted_unifrac
    normalized=normalized, unweighted=False)
  File "C:\ProgramData\Anaconda3\envs\mtDNA\lib\site-packages\skbio\diversity\beta\_unifrac.py", line 315, in _setup_pairwise_unifrac
    _vectorize_counts_and_tree(counts, otu_ids, tree)
  File "C:\ProgramData\Anaconda3\envs\mtDNA\lib\site-packages\skbio\diversity\_util.py", line 113, in _vectorize_counts_and_tree
    counts_by_node = _nodes_by_counts(counts, otu_ids, tree_index)
  File "skbio/diversity/_phylogenetic.pyx", line 213, in skbio.diversity._phylogenetic._nodes_by_counts (skbio/diversity/_phylogenetic.c:2641)
  File "skbio/diversity/_phylogenetic.pyx", line 68, in skbio.diversity._phylogenetic._traverse_reduce (skbio/diversity/_phylogenetic.c:1832)
ValueError: Buffer dtype mismatch, expected 'DTYPE_t' but got 'long'
```

The versions are:
Python 3.7.5
conda 4.7.12
scikit-bio 0.5.5

Please, help to fix it.

**Comment by ebolyen** [comment]
Thanks for the report and example @AaronBlare!
@wasade would you happen to recognize what is happening here?

(Also you might check out the [unifrac](https://github.com/biocore/unifrac) package in the meanwhile.)

**Comment by wasade** [comment]
Guessing that it's unhappy with the `int`s in the count vectors rather than floats. Or, a weird incompatibility with windows. I'm unable to recreate in py36, checking on py37 in a second:

```python
(qiime2-2019.10) 15:32:46 (dtmcdonald@here):~$ ipython
Python 3.6.7 | packaged by conda-forge | (default, Feb 28 2019, 02:16:08)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.9.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from io import StringIO
   ...: from skbio.tree import TreeNode
   ...: from skbio.diversity.beta import unweighted_unifrac
   ...:
   ...: tree = TreeNode.read(StringIO(
   ...:     '(((((OTU1:0.5,OTU2:0.5):0.5,OTU3:1.0):1.0):0.0,'
   ...:     '(OTU4:0.75,(OTU5:0.5,((OTU6:0.33,OTU7:0.62):0.5'
   ...:     ',OTU8:0.5):0.5):0.5):1.25):0.0)root;'))
   ...:
   ...: u_counts = [1, 0, 0, 4, 1, 2, 3, 0]
   ...: v_counts = [0, 1, 1, 6, 0, 1, 0, 0]
   ...: otu_ids = ['OTU1', 'OTU2', 'OTU3', 'OTU4', 'OTU5', 'OTU6', 'OTU7', 'OTU8']
   ...:
   ...: uu = unweighted_unifrac(u_counts, v_counts, otu_ids, tree)

In [2]:
```

**Comment by wasade** [comment]
Seems to work on py37. Best guess is this is a cython + windows issue, but I don't have a means to test that out. 

```python
(py37-base) 15:41:52 (dtmcdonald@here):~$ ipython
Python 3.7.5 (default, Oct 25 2019, 10:52:18)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.10.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from io import StringIO
   ...: from skbio.tree import TreeNode
   ...: from skbio.diversity.beta import unweighted_unifrac
   ...:
   ...: tree = TreeNode.read(StringIO(
   ...:     '(((((OTU1:0.5,OTU2:0.5):0.5,OTU3:1.0):1.0):0.0,'
   ...:     '(OTU4:0.75,(OTU5:0.5,((OTU6:0.33,OTU7:0.62):0.5'
   ...:     ',OTU8:0.5):0.5):0.5):1.25):0.0)root;'))
   ...:
   ...: u_counts = [1, 0, 0, 4, 1, 2, 3, 0]
   ...: v_counts = [0, 1, 1, 6, 0, 1, 0, 0]
   ...: otu_ids = ['OTU1', 'OTU2', 'OTU3', 'OTU4', 'OTU5', 'OTU6', 'OTU7', 'OTU8']
   ...:
   ...: uu = unweighted_unifrac(u_counts, v_counts, otu_ids, tree)

In [2]:
```

**Comment by wasade** [comment]
@AaronBlare, can you try doing the following and see if it works?

```python
import numpy as np
uu = unweighted_unifrac(np.asarray(u_counts, dtype=float), np.asarray(v_counts, dtype=float), otu_ids, tree)
```

**Comment by AaronBlare** [comment]
@wasade, I receive the same error.

**Comment by wasade** [comment]
That suggests this may be an issue with Windows and I don't have access to a Windows system. Was skbio installed by source? I'm wondering whether the Cython C code may need to be regenerated.

**Comment by jmol0917** [comment]
Hello, I am experiencing the same issue, also a Windows user. Is there any chance a fix has been found?

**Comment by seberg** [comment]
Just a quick flyby comment. I could create a PR, but I don't like band-aid fixes, and I am not quite sure if this is one.

There are two things I noticed:

1. You are using `np.int64`, which is good, but it seems to me likely that `np.intp` which is 64bit on 64bit systems and 32bit on 32bit systems might make more sense for `DTYPE_t`.
2. You are using `astype` in a few places, but it is missing in one place, but the original culprit is earlier, so I do not know if you want to add the `astype` or rather only fix it in the tree code.

The following diff should fix it, the `copy=False` is just a fly-by, you should add it to avoid unnecessary copies.  I expect the python side second fix/file is sufficient to solve the problem (without any recompilation necessary).

```diff
diff --git a/skbio/diversity/_phylogenetic.pyx b/skbio/diversity/_phylogenetic.pyx
index 91dfbae90..48ebc9e0a 100644
--- a/skbio/diversity/_phylogenetic.pyx
+++ b/skbio/diversity/_phylogenetic.pyx
@@ -177,7 +177,7 @@ def _nodes_by_counts(np.ndarray counts,
 
     # allow counts to be a vector
     counts = np.atleast_2d(counts)
-    counts = counts.astype(DTYPE)
+    counts = counts.astype(DTYPE, copy=False)
 
     # determine observed IDs. It may be possible to unroll these calls to
     # squeeze a little more performance
@@ -210,6 +210,6 @@ def _nodes_by_counts(np.ndarray counts,
         for j in range(n_count_vectors):
             count_array[otus_in_nodes[i], j] = counts_t[observed_indices[i], j]
 
-    _traverse_reduce(indexed['child_index'], count_array)
+    _traverse_reduce(indexed['child_index'].astype(DTYPE, copy=False), count_array)
 
     return count_array
diff --git a/skbio/tree/_tree.py b/skbio/tree/_tree.py
index f8c589b66..4aaf676c6 100644
--- a/skbio/tree/_tree.py
+++ b/skbio/tree/_tree.py
@@ -2848,7 +2848,7 @@ class TreeNode(SkbioObject):
             child_index.append((self.id,
                                 self.children[0].id,
                                 self.children[-1].id))
-        child_index = np.asarray(child_index)
+        child_index = np.asarray(child_index, dtype=np.int64)
         child_index = np.atleast_2d(child_index)
 
         return id_index, child_index
```

**Comment by wasade** [comment]
@seberg That seems like a reasonable diff! I don't think this is a bandaid as it improves the type specificity, and we'd welcome a PR! 

I do not know if this resolves issues for Windows users, however we do not currently test for windows support so there may be other problematic areas of the codebase.
