### ISSUE TITLE
skbio.stats.distance._base.DistanceMatrixError: Data must be symmetric and cannot contain NaNs.

### ISSUE THREAD

**Issue by nick-youngblut** [biocore/scikit-bio#1733]
I'm using a `qiime diversity beta-phylogenetic` (version `2020.8`) and getting the following error:

```
More threads were requested than stripes. Using -1509715504 threads.
Traceback (most recent call last):
  File "/ebio/abt3_projects/software/dev/ll_pipelines/llmgp/.snakemake/conda/d64706f7/lib/python3.6/site-packages/q2cli/commands.py", line 329, in __call__
    results = action(**arguments)
  File "<decorator-gen-399>", line 2, in beta_phylogenetic
  File "/ebio/abt3_projects/software/dev/ll_pipelines/llmgp/.snakemake/conda/d64706f7/lib/python3.6/site-packages/qiime2/sdk/action.py", line 245, in bound_callable
    output_types, provenance)
  File "/ebio/abt3_projects/software/dev/ll_pipelines/llmgp/.snakemake/conda/d64706f7/lib/python3.6/site-packages/qiime2/sdk/action.py", line 484, in _callable_executor_
    outputs = self._callable(scope.ctx, **view_args)
  File "/ebio/abt3_projects/software/dev/ll_pipelines/llmgp/.snakemake/conda/d64706f7/lib/python3.6/site-packages/q2_diversity/_beta/_pipeline.py", line 32, in beta_phylogenetic
    bypass_tips=bypass_tips)
  File "<decorator-gen-536>", line 2, in weighted_unifrac
  File "/ebio/abt3_projects/software/dev/ll_pipelines/llmgp/.snakemake/conda/d64706f7/lib/python3.6/site-packages/qiime2/sdk/action.py", line 245, in bound_callable
    output_types, provenance)
  File "/ebio/abt3_projects/software/dev/ll_pipelines/llmgp/.snakemake/conda/d64706f7/lib/python3.6/site-packages/qiime2/sdk/action.py", line 390, in _callable_executor_
    output_views = self._callable(**view_args)
  File "<decorator-gen-397>", line 2, in weighted_unifrac
  File "/ebio/abt3_projects/software/dev/ll_pipelines/llmgp/.snakemake/conda/d64706f7/lib/python3.6/site-packages/q2_diversity_lib/_util.py", line 49, in _disallow_empty_tables
    return wrapped_function(*args, **kwargs)
  File "<decorator-gen-396>", line 2, in weighted_unifrac
  File "/ebio/abt3_projects/software/dev/ll_pipelines/llmgp/.snakemake/conda/d64706f7/lib/python3.6/site-packages/q2_diversity_lib/_util.py", line 92, in _validate_requested_cpus
    return wrapped_function(*bound_arguments.args, **bound_arguments.kwargs)
  File "/ebio/abt3_projects/software/dev/ll_pipelines/llmgp/.snakemake/conda/d64706f7/lib/python3.6/site-packages/q2_diversity_lib/beta.py", line 170, in weighted_unifrac
    bypass_tips=bypass_tips)
  File "/ebio/abt3_projects/software/dev/ll_pipelines/llmgp/.snakemake/conda/d64706f7/lib/python3.6/site-packages/unifrac/_methods.py", line 212, in weighted_unnormalized
    variance_adjusted, 1.0, bypass_tips, threads)
  File "unifrac/_api.pyx", line 102, in unifrac._api.ssu
  File "/ebio/abt3_projects/software/dev/ll_pipelines/llmgp/.snakemake/conda/d64706f7/lib/python3.6/site-packages/skbio/stats/distance/_base.py", line 106, in __init__
    self._validate(data, ids)
  File "/ebio/abt3_projects/software/dev/ll_pipelines/llmgp/.snakemake/conda/d64706f7/lib/python3.6/site-packages/skbio/stats/distance/_base.py", line 873, in _validate
    "Data must be symmetric and cannot contain NaNs.")
skbio.stats.distance._base.DistanceMatrixError: Data must be symmetric and cannot contain NaNs.
```

I have 6 samples, and if I add a `print(data.T)` just prior to line 873, I get:

```
[[ 0. nan nan nan nan nan]
 [nan  0. nan nan nan nan]
 [nan nan  0. nan nan nan]
 [nan nan nan  0. nan nan]
 [nan nan nan nan  0. nan]
 [nan nan nan nan nan  0.]]
```

The count table has plenty of counts (`qiime diversity beta`, `qiime diversity alpha`, and `qiime diversity alpha-phylogenetic` all work). The phylogeny was taken directly from the GTDB. It works with `qiime diversity alpha-phylogenetic`, so why doesn't it work for `qiime diversity beta-phylogenetic`?

**Comment by nick-youngblut** [comment]
Printing at Line95 after `def __init__(self, data, ids=None):` show:

```
[nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan]
```

I don't know where the code is for `unifrac.ssu()`, so I can't trace this error any further back.

**Comment by mortonjt** [comment]
@seberg @wasade 

It is also worthwhile to see if the tree is kosher (i.e. are there branches that do not have any lengths).

**Comment by thermokarst** [comment]
xref: https://forum.qiime2.org/t/feature-ids-must-be-present-as-tip-names/17284

**Comment by nick-youngblut** [comment]
@thermokarst Sorry for the xref, but I do believe that this is specifically a sckit-bio (and probably a biocore/unifrac issue).

If it is just the tree (I'm not sure yet), it would be helpful to have a couple of checks for possible issues with branch lengths, tip labels, etc. to help the user troubleshoot. @mortonjt great idea to look at the branch lengths! I found 2 edges in the tree that don't have branch lengths. I'll try adding some and see if that fixes the issue. I'm guessing that scikit-bio or biocore-unifrac is assuming existing branch lengths without checking for missing/NA values, thus leading to all NaNs for calculated UniFrac values.

**Comment by mortonjt** [comment]
The easy way to test this is to impute those lengths with 0, namely
```python
from skbio import TreeNode
tree = TreeNode.read('tree.nwk')
for n in tree.levelorder():
    if n.length is None:
        n.length = 0
tree.write('new_tree.nwk')
```

If that did fix it, then yes, we should throw an error.

**Comment by nick-youngblut** [comment]
Yep, adding values for the missing branch lengths fixed the issue. It would be great if skbio threw an error for users like me that try to use messed-up trees.

**Comment by wasade** [comment]
This behavior is "correct" in that a tree with missing edges is not valid for UniFrac, and in scikit-bio we specifically [test](https://github.com/biocore/scikit-bio/pull/1027/files#diff-cb936f9f75f5e74098d08925b8e7124d5e4a77653815c047e7f61d7b6c1548a0R213-R220) that we cannot produce a result from that scenario. I would be :+1: for allowing `TreeNode` to default to a `length` of `0.0`. This represented a divergence of behavior on the port from PyCogent's `PhyloNode`, and [noted](https://github.com/biocore/scikit-bio/pull/192#issuecomment-38459410) during the port. I *think* that decision bore out from group discussion prior to the port, but I can't track those notes down right now. 

In `biocore/unifrac`, we opted to default missing edges to a length of `0.0` as shown in this [test](https://github.com/biocore/unifrac/blob/master/sucpp/test_su.cpp#L258-L279). I'm not sure why `nan`s are in this distance matrix, and have asked @nick-youngblut by way of `biocore/unifrac` for the input data.

**Comment by wasade** [comment]
Tracked the issue down. The tree contains valid but unexpected edges. Specifically, the `d__Bacteria` and `d__Archaea` edges are `NaN` within the Newick file itself. Both scikit-bio and unifrac parse these as floats, as `NaN` is a valid floating point number. `NaN is not None` though, so a check through the tree to replace missing edges will fail. It is not clear why it seemed to work in this thread above, but I've been unable to recreate a working example with `is None` based replacement on the unifrac thread -- more detail [here](https://github.com/biocore/unifrac/issues/116#issuecomment-720655242). 

While this is technically a valid tree, it does contain unexpected properties. I'm inclined to argue that it is *incorrect* to infer `NaN`s as a `0.0` branch length, and instead favor a warning or an exception.

**Comment by nick-youngblut** [comment]
Thanks so much to you all for responding so quickly to my issue. I was too quick to post an issue without fully inspecting my input newick file. I'll try to be more cautious next time (patience with software has never been easy for me). I was just hoping to help debug an issue with skbio and jumped on it too quickly. Thanks again.

**Comment by wasade** [comment]
@nick-youngblut, thank you for the report!! This is an edge case that should be handled gracefully, and in an informative manner, which is not currently what is happening. To be clear: this is a problem with skbio and unifrac. The nature of the resolution, of either mapping `NaN` to `0.0` or improved error handling, still needs to be determined though.

**Comment by thermokarst** [comment]
@nick-youngblut - can you make a note to update your QIIME 2 Forum post with some link or summary of the resolution?

**Comment by nick-youngblut** [comment]
Sure! I've added a note at https://forum.qiime2.org/t/feature-ids-must-be-present-as-tip-names/17284/11

**Comment by wasade** [comment]
Closing as this issue has been moved to biocore/unifrac
