### ISSUE TITLE
Cannot install in a clean virtualenv

### ISSUE THREAD

**Issue by EmiliaW** [biocore/scikit-bio#1734]
A Python package should always be able to install itself in an empty virtualenv and handle dependencies automatically. Trying to do this with scikit-bio fails because numpy is imported before the normal setup_requires directive has a chance to install it:
```python
$ git clone https://github.com/biocore/scikit-bio.git
$ cd scikit-bio
$ python3 -m venv build_env
$ source build_env/bin/activate
$ python3 -m pip install -e .
Obtaining file:///ewo/scikit-bio
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/ewo/scikit-bio/setup.py", line 21, in <module>
        import numpy as np
    ModuleNotFoundError: No module named 'numpy'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1
```

**Comment by mortonjt** [comment]
This is a known problem. The solution here is to install numpy first, then
install skbio.

If you have thoughts on how to solve this, pull requests are always welcome
:)

**Comment by danodonovan** [comment]
@mortonjt - this issue is solved in `master` - see #1690
It would be great if there could be a new scikit-bio release which includes this.

**Comment by Midnighter** [comment]
A release would be nice indeed. I use tox for testing and it's a bit trickier there to just install numpy first.

**Comment by wasade** [comment]
Solved in #1690
