### ISSUE TITLE
UniFrac fails on Windows

### ISSUE THREAD

**Issue by fluhus** [biocore/scikit-bio#1788]
Hi,

I am not sure if Windows is officially supported, but I installed `skbio 0.5.6` on my Windows machine.

After successfully running:

```
pip install --force-reinstall scikit-bio
```

The following code fails on Windows but succeeds on Linux:

```python
from io import StringIO

import numpy as np
from skbio import TreeNode
from skbio.diversity import beta_diversity

beta_diversity('unweighted_unifrac',
               np.array([[1, 1, 0], [0, 1, 1]]),
               otu_ids=['s1', 's2', 's3'],
               tree=TreeNode.read(StringIO('((s1:1,s2:3):0.1,s3:5);')))
```

Output:

```
Traceback (most recent call last):
  File "c:\Users\docto\Desktop\rstuff\unifrac.py", line 10, in <module>
    beta_diversity('unweighted_unifrac',
  File "C:\dev\tools\python\lib\site-packages\skbio\diversity\_driver.py", line 354, in beta_diversity
    metric, counts_by_node = _setup_multiple_unweighted_unifrac(
  File "C:\dev\tools\python\lib\site-packages\skbio\diversity\beta\_unifrac.py", line 485, in _setup_multiple_unweighted_unifrac
    _setup_multiple_unifrac(counts, otu_ids, tree, validate)
  File "C:\dev\tools\python\lib\site-packages\skbio\diversity\beta\_unifrac.py", line 452, in _setup_multiple_unifrac
    _vectorize_counts_and_tree(counts, otu_ids, tree)
  File "C:\dev\tools\python\lib\site-packages\skbio\diversity\_util.py", line 126, in _vectorize_counts_and_tree
    counts_by_node = _nodes_by_counts(counts, otu_ids, tree_index)
  File "skbio/diversity/_phylogenetic.pyx", line 213, in skbio.diversity._phylogenetic._nodes_by_counts
  File "skbio/diversity/_phylogenetic.pyx", line 68, in skbio.diversity._phylogenetic._traverse_reduce
ValueError: Buffer dtype mismatch, expected 'DTYPE_t' but got 'long'
```

**Comment by wasade** [comment]
@fluhus we don't currently test for Windows so cannot guarantee support on that platform, and I'm closing as this is out of scope for the project. 

Are you able to use Windows Subsystem for Linux?

**Comment by fluhus** [comment]
Thanks @wasade for your response.
I switched to a Linux machine and was able to use the library from there.

**Comment by wasade** [comment]
That's great, thanks. FWIW, the implementation here, while moderately optimized, uses an older algorithm. If you're operating on large tables, or are impatient like me, an aggressively optimized version is available in bioconda under `unifrac-binaries` (command line binary and shared library) with Python bindings in bioconda under `unifrac`. These are the libraries that, for example, QIIME 2 uses behind the scenes now and which also implement Generalized UniFrac and Variance adjusted UniFrac.

**Comment by fluhus** [comment]
Sorry for the late response.
I looked into `unifrac-binaries` as you suggested and found the executables. Thank you for the advice!
