### ISSUE TITLE
Tests fail to run: ModuleNotFoundError: No module named 'skbio.metadata._intersection'

### ISSUE THREAD

**Issue by yurivict** [biocore/scikit-bio#1846]
```
===>  Testing for py39-scikit-bio-0.5.7_2
===>   py39-scikit-bio-0.5.7_2 depends on package: py39-pytest>=7,1 - found
===>   py39-scikit-bio-0.5.7_2 depends on file: /usr/local/bin/python3.9 - found
cd /usr/ports/biology/py-scikit-bio/work-py39/scikit-bio-0.5.7 && /usr/bin/env XDG_DATA_HOME=/usr/ports/biology/py-scikit-bio/work-py39  XDG_CONFIG_HOME=/usr/ports/biology/py-scikit-bio/work-py39  XDG_CACHE_HOME=/usr/ports/biology/py-scikit-bio/work-py39/.cache  HOME=/usr/ports/biology/py-scikit-bio/work-py39 PATH=/usr/local/libexec/ccache:/usr/ports/biology/py-scikit-bio/work-py39/.bin:/home/yuri/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin PKG_CONFIG_LIBDIR=/usr/ports/biology/py-scikit-bio/work-py39/.pkgconfig:/usr/local/libdata/pkgconfig:/usr/local/share/pkgconfig:/usr/libdata/pkgconfig MK_DEBUG_FILES=no MK_KERNEL_SYMBOLS=no SHELL=/bin/sh NO_LINT=YES LDSHARED="cc -shared" PYTHONDONTWRITEBYTECODE= PYTHONOPTIMIZE= PREFIX=/usr/local  LOCALBASE=/usr/local  CC="cc" CFLAGS="-O2 -pipe  -fstack-protector-strong -fno-strict-aliasing "  CPP="cpp" CPPFLAGS=""  LDFLAGS=" -fstack-protector-strong " LIBS=""  CXX="c++" CXXFLAGS="-O2 -pipe -fstack-protector-strong -fno-strict-aliasing  "  MANPREFIX="/usr/local" CCACHE_DIR="/tmp/.ccache" BSD_INSTALL_PROGRAM="install  -s -m 555"  BSD_INSTALL_LIB="install  -s -m 0644"  BSD_INSTALL_SCRIPT="install  -m 555"  BSD_INSTALL_DATA="install  -m 0644"  BSD_INSTALL_MAN="install  -m 444" PYTHONPATH=/usr/ports/biology/py-scikit-bio/work-py39/stage/usr/local/lib/python3.9/site-packages /usr/local/bin/python3.9 -m pytest -k '' -rs -v -o addopts= 
ERROR: while parsing the following warning configuration:

  ignore::skbio.util.SkbioWarning

This error occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1690, in parse_warning_filter
    category: Type[Warning] = _resolve_warning_category(category_)
  File "/usr/local/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1728, in _resolve_warning_category
    m = __import__(module, None, None, [klass])
  File "/usr/ports/biology/py-scikit-bio/work-py39/scikit-bio-0.5.7/skbio/__init__.py", line 11, in <module>
    import skbio.io  # noqa
  File "/usr/ports/biology/py-scikit-bio/work-py39/scikit-bio-0.5.7/skbio/io/__init__.py", line 243, in <module>
    import_module('skbio.io.format.clustal')
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/ports/biology/py-scikit-bio/work-py39/scikit-bio-0.5.7/skbio/io/format/clustal.py", line 148, in <module>
    from skbio.alignment import TabularMSA
  File "/usr/ports/biology/py-scikit-bio/work-py39/scikit-bio-0.5.7/skbio/alignment/__init__.py", line 203, in <module>
    from ._tabular_msa import TabularMSA
  File "/usr/ports/biology/py-scikit-bio/work-py39/scikit-bio-0.5.7/skbio/alignment/_tabular_msa.py", line 17, in <module>
    from skbio.metadata._mixin import MetadataMixin, PositionalMetadataMixin
  File "/usr/ports/biology/py-scikit-bio/work-py39/scikit-bio-0.5.7/skbio/metadata/__init__.py", line 27, in <module>
    from ._interval import Interval, IntervalMetadata
  File "/usr/ports/biology/py-scikit-bio/work-py39/scikit-bio-0.5.7/skbio/metadata/_interval.py", line 13, in <module>
    from ._intersection import IntervalTree
ModuleNotFoundError: No module named 'skbio.metadata._intersection'
```

Version: 0.5.7
Python-3.9
FreeBSD 13.1

**Comment by wasade** [comment]
Hi @yurivict, sorry for the delay. How was skbio installed? It looks as though a Cython library may not have been compiled.

**Comment by yurivict** [comment]
Hi @wasade ,

Cython appears to build modules fine.
The file ```/usr/local/lib/python3.9/site-packages/skbio/metadata/_intersection.cpython-39.so``` is installed.
This import succeeds:
```
from skbio.metadata._intersection import IntervalTree
```

It only fails from tests.

Version: 0.5.9

Yuri

**Comment by yurivict** [comment]
No, it installs successfully.

It is built using "build" and installed using "installer" packages.

The problem seems to be only in tests.
