### ISSUE TITLE
OrdinationResults fails to write

### ISSUE THREAD

**Issue by gibsramen** [biocore/scikit-bio#1853]
When trying to write an `skbio.stats.ordination.OrdinationResults` object to a file, the `.write()` method fails. Seems to be a NumPy deprecation.

# Reproducible example:

```python
import biom
from skbio.stats.ordination import pcoa
from skbio.diversity import beta
from scipy.spatial.distance import pdist, squareform

tbl = biom.example_table
counts = tbl.transpose().to_dataframe(dense=True)
dm = squareform(pdist(counts.values, "braycurtis"))

ord_res = pcoa(dm)
ord_res.write("./ordination.txt"
```

<details open>
<summary>Error Message</summary>
<br>

```
/home/grahman/miniconda3/envs/gemelli-dev/lib/python3.8/site-packages/skbio/io/format/ordination.py:414: FutureWarning: In the future `np.str` will be defined as the corresponding NumPy scalar.
  formatted_vector = '\t'.join(np.asarray(vector, dtype=np.str))
Traceback (most recent call last):
  File "bug.py", line 11, in <module>
    ord_res.write("./ordination.txt")
  File "/home/grahman/miniconda3/envs/gemelli-dev/lib/python3.8/site-packages/skbio/io/registry.py", line 673, in write
    return registry.write(self, into=file, format=format, **kwargs)
  File "/home/grahman/miniconda3/envs/gemelli-dev/lib/python3.8/site-packages/skbio/io/registry.py", line 619, in write
    writer(obj, into, **kwargs)
  File "/home/grahman/miniconda3/envs/gemelli-dev/lib/python3.8/site-packages/skbio/io/registry.py", line 1082, in wrapped_writer
    writer_function(obj, fhs[-1], **kwargs)
  File "/home/grahman/miniconda3/envs/gemelli-dev/lib/python3.8/site-packages/skbio/io/format/ordination.py", line 370, in _ordination_results_to_ordination
    _write_vector_section(fh, 'Eigvals', obj.eigvals)
  File "/home/grahman/miniconda3/envs/gemelli-dev/lib/python3.8/site-packages/skbio/io/format/ordination.py", line 387, in _write_vector_section
    fh.write(_format_vector(vector.values))
  File "/home/grahman/miniconda3/envs/gemelli-dev/lib/python3.8/site-packages/skbio/io/format/ordination.py", line 414, in _format_vector
    formatted_vector = '\t'.join(np.asarray(vector, dtype=np.str))
  File "/home/grahman/miniconda3/envs/gemelli-dev/lib/python3.8/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'str'.
`np.str` was a deprecated alias for the builtin `str`. To avoid this error in existing code, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecation
```

</details>

# Versions

* NumPy: `1.24.3`
* Scikit-Bio: `0.5.6`
* Scipy: `1.10.1`

**Comment by wasade** [comment]
What about with skbio 0.5.8? It looks like this may have been fixed 2 years ago, see https://github.com/biocore/scikit-bio/blame/master/skbio/io/format/ordination.py#L414

**Comment by gibsramen** [comment]
That'll do it. Thanks - should've checked the version. I think I installed via the `anaconda` channel (which is only up to 0.5.6) instead of the `conda-forge` channel. Updating to 0.5.8 works.
