### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by quiqua** [biocore/scikit-bio#702]
Hey there!
Did you successfully compile the cython extension on windows?
I'm using Python 2.7 running in a virtual Windows 7 32 bit machine, inlcuded a `"stdint.h"` file like the Pandas project does ([like here](https://github.com/pydata/pandas/tree/master/pandas/src/headers))(since python 2.7. relies on MSVC 2008 and this version does not include this header). 
Yet there seems to be a problem with the `__m128i` type provided by `<emmintrin.h>`
```
...
skbio/alignment/_lib/ssw.c(196) : error C2275: '__m128i' : illegal use of this type as an expression
            C:\Program Files\Microsoft Visual Studio 9.0\VC\INCLUDE\emmintrin.h(45) : see declaration of '__m128i'
```

**Comment by mattfullerton** [comment]
For those wanting to play around with a source tree that does actually compile (pip install -e <folderpath>, you can find one here: https://github.com/mattfullerton/scikit-bio/commit/731b133db87867e4f2ca09e787991ca1fb194d30

I had to do a lot of deciphering here and in #780 to figure out what actually needs changing (that pull request in and of itself does not fix the compiling problem). I have no reason to believe this compile will be any better than the reported binaries that don't work, but who knows. Hence, I'm not submitting a pull request right now.

**Comment by ebolyen** [comment]
Oops! Trying to comment. Thanks for the exploration @mattfullerton! This is really cool. Does anyone have access to a i686 machine to make sure that this doesn't also break that build?

**Comment by anderspitman** [comment]
We discussed setting up a windows VM on powertrip a while back, but that sort of got pushed to the side. I can open an issue for that if it's still desirable.

**Comment by ebolyen** [comment]
:+1: I think we do need something like that if we are ever going to really fix this.

**Comment by jairideout** [comment]
:+1:

**Comment by methodds** [comment]
I just tried @mattfullerton 's windows version and while compiling worked just fine I cannot import skbio due to the error:

````
Python 3.5.0 |Anaconda 2.4.0 (64-bit)| (default, Oct 20 2015, 07:26:33) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import skbio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda3\lib\site-packages\scikit_bio-0.4.0.dev0-py3.5-win-amd64.egg\skbio\__init__.py", line 14, in <modul
>
    import skbio.io  # noqa
  File "C:\Anaconda3\lib\site-packages\scikit_bio-0.4.0.dev0-py3.5-win-amd64.egg\skbio\io\__init__.py", line 225, in <m
dule>
    import_module('skbio.io.format.clustal')
  File "C:\Anaconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Anaconda3\lib\site-packages\scikit_bio-0.4.0.dev0-py3.5-win-amd64.egg\skbio\io\format\clustal.py", line 113,
in <module>
    from skbio.sequence import Sequence
  File "C:\Anaconda3\lib\site-packages\scikit_bio-0.4.0.dev0-py3.5-win-amd64.egg\skbio\sequence\__init__.py", line 290,
in <module>
    from ._sequence import Sequence
  File "C:\Anaconda3\lib\site-packages\scikit_bio-0.4.0.dev0-py3.5-win-amd64.egg\skbio\sequence\_sequence.py", line 28,
in <module>
    from skbio._base import SkbioObject
  File "C:\Anaconda3\lib\site-packages\scikit_bio-0.4.0.dev0-py3.5-win-amd64.egg\skbio\_base.py", line 18, in <module>
    import matplotlib.pyplot as plt
  File "C:\Anaconda3\lib\site-packages\matplotlib\pyplot.py", line 109, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "C:\Anaconda3\lib\site-packages\matplotlib\backends\__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "C:\Anaconda3\lib\site-packages\matplotlib\backends\backend_qt4agg.py", line 17, in <module>
    from .backend_qt5agg import NavigationToolbar2QTAgg
  File "C:\Anaconda3\lib\site-packages\matplotlib\backends\backend_qt5agg.py", line 18, in <module>
    from .backend_qt5 import QtCore
  File "C:\Anaconda3\lib\site-packages\matplotlib\backends\backend_qt5.py", line 31, in <module>
    from .qt_compat import QtCore, QtGui, QtWidgets, _getSaveFileName, __version__
  File "C:\Anaconda3\lib\site-packages\matplotlib\backends\qt_compat.py", line 91, in <module>
    from PyQt4 import QtCore, QtGui
ImportError: DLL load failed: The specified procedure could not be found.
````
Any idea how to fix this?

**Comment by jairideout** [comment]
@methodds this looks like a matplotlib installation issue. Are you able to successfully run

```python
import matplotlib.pyplot as plt
```

in an interactive session?
